"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Code2, X } from "lucide-react";
import { useEffect, useState } from "react";

type Project = { title: string; description: string; tech: string[]; image: string; github?: string; details?: string[] };
const projects: Project[] = [
  { title: "Vitamin Vision", description: "Micronutrient deficiency detection with a clean ML pipeline and inference integration.", tech: ["Python", "TensorFlow", "OpenCV", "Flask"], image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2014%2C%202026%2C%2009_27_34%20PM-jXX8oA6qBWYjLUAQUEn8IHWruYfrPc.png", github: "https://github.com/adar-shh04/VitaminVision", details: ["Structured training and evaluation pipeline", "Inference-ready backend integration", "Clear separation of data, model, and serving"] },
  { title: "Data Sensei", description: "Natural language to SQL dashboard for synthetic gym supplement consumption data — ask questions, get instant insights.", tech: ["Python", "SQL", "NLP", "Streamlit"], image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2014%2C%202026%2C%2009_28_58%20PM-MeZLx5clDCXJoRg9d8Ze1KLPboFA5d.png", github: "https://github.com/adar-shh04/Data-Sensei", details: ["LLM-to-SQL query interface", "Synthetic dataset modelling supplement consumption", "Interactive dashboard with real-time results"] },
  { title: "LogisticsAuto", description: "Industry-grade supply chain automation using OCR, Gemini NLP, and anomaly detection.", tech: ["FastAPI", "PostgreSQL", "Redis", "Docker"], image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2014%2C%202026%2C%2009_30_18%20PM-gMS9qUhNHz2G0iIOnPnoJt2ZQJhthe.png", github: "https://github.com/adar-shh04/Logistics-Automation", details: ["AI-driven document parsing via Google Gemini", "Distributed task queue with Redis and Celery", "Production-ready anomaly detection"] },
  { title: "Telco Customer Intelligence", description: "End-to-end customer intelligence dashboard for telecom churn analysis, segmentation, and revenue impact modelling.", tech: ["Python", "Pandas", "Scikit-learn", "Plotly"], image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2014%2C%202026%2C%2009_31_39%20PM-VBvKtkR38ysXdIx98kWmY9sgnhiW1C.png", github: "https://github.com/adar-shh04/Telco-Customer-Intelligence-Dashboard", details: ["Customer churn prediction with ML classification", "RFM segmentation and cohort revenue analysis", "Interactive dashboard with drill-down filters"] },
  { title: "Financial Risk Intelligence System", description: "Enterprise ML pipeline combining ensemble models, Monte Carlo VaR, and SHAP explainability for customer churn risk analytics.", tech: ["Python", "XGBoost", "SHAP", "Streamlit"], image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gemini_Generated_Image_rz3hcarz3hcarz3h-1QK1PFwixSCqyoelNT0SeIPquTaFJA.png", github: "https://github.com/adar-shh04/Financial-Risk-Intelligence-System", details: ["Calibrated ensemble model for risk scoring", "Monte Carlo VaR with 10,000 simulations", "SHAP explainability and stress testing"] },
];

export default function ProjectsSection() {
  const [index, setIndex] = useState(0); const [open, setOpen] = useState<Project | null>(null); const current = projects[index];
  useEffect(() => { if (!open) return; const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(null); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [open]);
  const move = (step: number) => setIndex((index + step + projects.length) % projects.length);
  return <section id="projects" className="section-shell scroll-mt-24"><div className="section-heading flex-wrap"><div><p className="eyebrow"><span className="text-emerald-primary">02</span> / selected work</p><h2>Built for the real world.</h2><p className="mt-4 max-w-xl text-white/55">A rotating set of systems where product clarity meets technical depth.</p></div><div className="flex items-center gap-2"><span className="font-mono text-xs text-white/40">{String(index + 1).padStart(2, "0")} / {String(projects.length).padStart(2, "0")}</span><button onClick={() => move(-1)} className="icon-button" aria-label="Previous project"><ArrowLeft size={17} /></button><button onClick={() => move(1)} className="icon-button" aria-label="Next project"><ArrowRight size={17} /></button></div></div>
    <div className="relative min-h-[530px] overflow-hidden rounded-2xl border border-white/10 bg-[#0b101f]/70 p-3 md:p-5"><div className="absolute inset-y-0 right-0 w-1/3 bg-emerald-primary/5 blur-3xl" aria-hidden="true" /><AnimatePresence mode="wait"><motion.button key={current.title} type="button" onClick={() => setOpen(current)} initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }} transition={{ duration: .35 }} className="group relative grid h-full min-h-[495px] w-full overflow-hidden rounded-xl border border-emerald-primary/30 bg-[#101620] text-left md:grid-cols-[1.1fr_.9fr] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-primary"><div className="relative min-h-64 overflow-hidden bg-black/30 md:min-h-full">{/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={current.image} alt={`${current.title} project preview`} className="h-full w-full object-contain p-2 transition-opacity duration-500 group-hover:opacity-95 md:p-4" loading={index === 0 ? "eager" : "lazy"} /><div className="absolute inset-0 bg-gradient-to-t from-[#101620] via-transparent to-transparent md:bg-gradient-to-r" /></div><div className="flex flex-col justify-between p-7 md:p-10"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-soft">case study / {String(index + 1).padStart(2, "0")}</p><h3 className="mt-5 max-w-lg text-3xl font-semibold tracking-[-.04em] text-white md:text-5xl">{current.title}</h3><p className="mt-5 max-w-lg text-base leading-7 text-white/60">{current.description}</p></div><div><div className="flex flex-wrap gap-2">{current.tech.map((tech) => <span key={tech} className="tag">{tech}</span>)}</div><span className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-emerald-soft">Open project details <ArrowRight size={16} /></span></div></div></motion.button></AnimatePresence></div>
    <div className="mt-4 flex gap-2">{projects.map((project, i) => <button key={project.title} onClick={() => setIndex(i)} aria-label={`Show ${project.title}`} className={`h-1 flex-1 rounded-full transition ${i === index ? "bg-emerald-primary" : "bg-white/15 hover:bg-white/30"}`} />)}</div>
    <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 grid place-items-center p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button className="absolute inset-0 bg-black/80" onClick={() => setOpen(null)} aria-label="Close project dialog" /><motion.div role="dialog" aria-modal="true" aria-labelledby="project-title" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-[#0b101f] p-7 shadow-2xl"><button onClick={() => setOpen(null)} className="absolute right-5 top-5 text-white/50 hover:text-white" aria-label="Close"><X size={19} /></button><p className="eyebrow">project details</p><h3 id="project-title" className="mt-3 text-3xl font-semibold text-white">{open.title}</h3><p className="mt-3 leading-7 text-white/60">{open.description}</p><ul className="mt-6 space-y-3 text-white/70">{open.details?.map((detail) => <li key={detail} className="flex gap-3"><span className="text-emerald-primary">—</span>{detail}</li>)}</ul><div className="mt-7 flex flex-wrap gap-2">{open.tech.map((tech) => <span key={tech} className="tag">{tech}</span>)}</div><a href={open.github} target="_blank" rel="noopener noreferrer" className="button-primary mt-8">View on GitHub <Code2 size={16} /></a></motion.div></motion.div>}</AnimatePresence>
  </section>;
}
